name: mpv-wayland
summary: mpv mediaplayer snap with a main focus on Wayland support
description: |
  Configuration files can be placed under /home/$USER/snap/mpv-wayland/common/.config/mpv/ directory.  
  YouTube should work out of the box.

  ___
  Allow access to /media, /run/media and /mnt:

  snap connect mpv-wayland:removable-media
source-code: https://github.com/iomezk/snap-mpv
license: GPL-2.0+
base: core22
confinement: strict
grade: stable
icon: icon.svg

apps:
  mpv-wayland:
    command: bin/mpv
    plugs:
    - audio-playback
    - home
    - network
    - opengl
    - removable-media
    - wayland
  yt-dlp:
    command: bin/yt-dlp
    plugs:
    - audio-playback
    - home
    - network
    - opengl
    - removable-media
    - wayland

environment:
  HOME: $SNAP_USER_COMMON
  XDG_CONFIG_HOME: $SNAP_USER_COMMON/.config
  XDG_CACHE_HOME: /
  PATH: $SNAP/bin:$PATH
  LD_LIBRARY_PATH: $SNAP/gui-lib/usr/lib:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio:$SNAP/lib
  XKB_CONFIG_ROOT: $SNAP/gui-lib/usr/share/X11/xkb
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/gui-lib/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  LIBVA_DRIVERS_PATH: $SNAP/gui-lib/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri
  MESA_SHADER_CACHE_DISABLE: "true"
  FONTCONFIG_PATH: $SNAP/gui-lib/etc/fonts
  FONTCONFIG_FILE: $SNAP/etc/fonts/fonts.conf
  PYTHONPATH: $SNAP/lib/python3.10/site-packages

plugs:
  gnome-42-2204:
    interface: content
    default-provider: gnome-42-2204
    target: gui-lib
  ffmpeg-2204:
    interface: content
    default-provider: ffmpeg-2204
    target: ffmpeg-platform

layout:
  /usr/share/font1:
    symlink: $SNAP/gui-lib/usr/share/fonts

adopt-info: mpv
parts:
  local:
    source: snap/local/
    source-type: local
    plugin: dump
    prime:
    - -patches/
  meson-deps:
    plugin: nil
    build-packages:
    - python3-pip
    - ninja-build
    override-build: |
      pip install meson
  mpv:
    after:
    - meson-deps
    - libplacebo
    source: https://github.com/mpv-player/mpv/archive/v0.37.0.tar.gz
    source-checksum: sha256/1d2d4adbaf048a2fa6ee134575032c4b2dad9a7efafd5b3e69b88db935afaddf
    source-type: tar
    build-snaps:
    - gnome-42-2204-sdk
    build-packages:
    - libavfilter-dev
    - libass-dev
    - liblua5.2-dev
    - libjpeg-turbo8-dev  # libjpeg-turbo package bug 2042483
    - jq
    override-pull: |
      craftctl default
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/mpv-fixed-runtime-dir.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/mpv-hwdec-enable.patch"
      patch -p1 -i "$CRAFT_PROJECT_DIR/snap/local/patches/mpv-no-global-conf.patch"
    build-environment: &buildenv
    - LDFLAGS: -lstdc++
    - PATH: /snap/gnome-42-2204-sdk/current/usr/bin${PATH:+:$PATH}
    - LD_LIBRARY_PATH: /snap/gnome-42-2204-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/gnome-42-2204-sdk/current/usr/lib:/snap/gnome-42-2204-sdk/current/usr/lib/vala-current:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    - PKG_CONFIG_PATH: /snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    plugin: meson
    meson-parameters:
    - --buildtype=release
    - --strip
    - --prefix=/
    - -Dbuild-date=false
    - -Dlua=enabled
    - -Dpulse=enabled
    - -Ddrm=enabled
    - -Degl=enabled
    - -Degl-wayland=enabled
    - -Dwayland=enabled
    - -Dvaapi-drm=disabled
    - -Dvaapi-wayland=enabled
    - -Dvaapi-x11=disabled
    - -Dx11=disabled
    - -Dmanpage-build=disabled
    override-build: |
      craftctl default
      craftctl set "version=$(jq -r .version meson-info/intro-projectinfo.json)"
    stage-packages:
    - libavfilter7
    - liblua5.2-0
    organize:
      etc/: share/  # hide etc/
      '**/lib*.so*': lib/
    prime:
    - -share
    - -usr
    # subdirs:
    - -lib/libpixbufloader*
    - -lib/libmfx_*
    - -lib/libmfx-*
    - -lib/libmfxhw*
    - -lib/libvdpau_*
    # library linter:
    - -lib/libdeflate*
    - -lib/libjbig*
    - -lib/libflite_cmu_grapheme*
    - -lib/libflite_cmu_indic*
    - -lib/libflite_cmu_time*
    - -lib/libicu*
    - -lib/liblua*-c++*
    - -lib/libsphinxad*
    - -lib/libtiff*
    - -lib/libtheora*
    - -lib/libzvbi-chains*
    # comm -12 <(find /snap/gnome-42-2204/current/ ! -type d -printf '%f\n' | sort -u) <(find /snap/mpv-wayland/current/ ! -type d -printf '%f\n' | sort -u)
    - -lib/libFLAC*
    - -lib/libX*
    - -lib/libasound*
    - -lib/libasyncns*
    - -lib/libcairo*
    - -lib/libdatrie*
    - -lib/libfontconfig*
    - -lib/libfribidi*
    - -lib/libgdk*
    - -lib/libgomp*
    - -lib/libgraphite*
    - -lib/libharfbuzz*
    - -lib/libjpeg*
    - -lib/libmp3lame*
    - -lib/libmpg123*
    - -lib/libogg*
    - -lib/libopenjp*
    - -lib/libopus*
    - -lib/libpango*
    - -lib/libpixman*
    - -lib/libpulse*
    - -lib/libquadmath*
    - -lib/librsvg*
    - -lib/libsamplerate*
    - -lib/libsndfile*
    - -lib/libspeex*
    - -lib/libthai*
    - -lib/libtwolame*
    - -lib/libva*
    - -lib/libvorbis*
    - -lib/libvpx*
    - -lib/libwebp*
    - -lib/libxcb*
    - -lib/libxml2*
  libplacebo:
    after:
    - meson-deps
    source: https://code.videolan.org/videolan/libplacebo.git
    source-commit: 2805a0d01c029084ab36bf5d0e3c8742012a0b27  # v6.338.1
    source-type: git
    source-depth: 1
    build-packages:
    - g++
    build-environment: *buildenv
    plugin: meson
    meson-parameters:
    - --buildtype=release
    - --prefix=/usr
    - --libdir=lib
    - -Ddefault_library=static
    prime:
    - -*
  yt-dlp:
    source: https://github.com/yt-dlp/yt-dlp.git
    source-commit: a0b19d319a6ce8b7059318fa17a34b144fde1785
    source-type: git
    source-depth: 1
    plugin: python
    override-build: |
      craftctl default
      cd "$CRAFT_PART_INSTALL"/lib/python*/site-packages
      IFS=$(printf '\t') find yt_dlp -name '*.pyc' | sed -r \
       's/.*/\0\t\0/; s#/__pycache__/#/#; s/\.cpython-[0-9]+\.pyc\t/.pyc\t/' | while read -r D S; do
        mv "$S" "$D"
      done
    prime:
    - bin/yt-dlp
    - lib/python*/site-packages/yt_dlp/**/*.pyc
